### ISSUE TITLE
Mismatch in band IDs

### ISSUE THREAD

**Issue by Zeklandia** [jpierel14/snsed#3]
Lines [283](https://github.com/jpierel14/snsed/blob/master/snsedextend/colorCalc.py#L283) and [291](https://github.com/jpierel14/snsed/blob/master/snsedextend/colorCalc.py#L291) of colorCalc.py compare the band ID in the lightcurve data with the band given in an entry of the `bandFit` (list) argument. If `bandFit` is `["r-z"]`, and the data uses `sdss::r`, `sdss::z`, then no data will be added to `blues` or `reds`, and the function will return the message:

> `Asked for color r-z but missing necessary band(s)`

**Comment by jpierel14** [comment]
This should be fixed in commit 2370957b376e3ff791adcc1aadd75c5f2eb0432a, let me know if it doesn't before I close out the issue.

**Comment by Zeklandia** [comment]
I'm using snsedextend 0.3.1 (latest available in PIP) and this still happens. I'll try supplying a band dictionary.

**Comment by jpierel14** [comment]
I assumed you were using the GitHub version and installing from source. I'll update pip if you're using that.

**Comment by jpierel14** [comment]
This has been fixed in version 0.3.2 on pip.

**Comment by Zeklandia** [comment]
This issue has been resolved through the combination of your changes to snsedextend and my changes to how I use it.
